### ISSUE TITLE
Tensorflow Quantum implementation?

### ISSUE THREAD

**Issue by nonconvexopt** [NoahBerner/quantum_bayesian_neural_networks#1]
Hi, your project seems really interesting and prominent to me. May I ask you why you used JAX instead of TF Quantum? I am considering implementing your work with TF Quantum, but I am wondering if there are reasons that JAX is more preferable, in terms of performances, readability, scalability, etc.

**Comment by NoahBerner** [comment]
Hi, thank you very much. It is nice to hear that you are taking interest in this project.

The reason why I used the JAX library has more to do with the Bayesian neural network (BNN) part of this implementation. By using JAX I gained a lot of controllability on how the BNN is implemented but still had the benefit of letting it run on a GPU without much effort. Although I had to implement the probability distribution of the quantum inner product estimation myself (and thus phase estimation, eigenvalue estimation and amplitude estimation), I still feel like this saved me time by not having to worry about GPU implementation and optimization.
Of course, that is not the only right way of doing it. If you find a fast way to combine a BNN implementation with TF Quantum, Qiskit or any other quantum library, that could be a great way to go forward. I must also admit that I am not too familiar with TF Quantum and its capabilities (more so with Qiskit for example) so I am not a great help there.

I hope this provides you with a sufficient answer. Otherwise feel free to ask again :) I am happy to help.

**Comment by nonconvexopt** [comment]
Thank you for your kind and detailed explanations. It takes a wrong time to understand your implementation at least a little bit. And it is hard to grasp a intuition on why the CIQP has the most reasonable uncertainties compared to CICP and QIQP.

At start, I just considered Quantum ML method like your project are methods which will efficiently parallelize the sampling process of Bayesian inference implicitly and calculate approximate integral values(like for posterior and predictive distribution?). But more and more studying Quantum Computation and your work, I got somewhat misunderstood the Quantum Computing. It is amazing that the project of this topic is proceeded.

Again, thank you for your effort and time! I will find out if the outcomes can be made with TF Quantum... haha
